config/routes.rb
require 'api_constraints'

Friendscan::Application.routes.draw do

  match "/faq" => "home#faq"
  match "/terms" => "home#terms"
  match "/privacy" => "home#privacy"
  namespace :api, defaults: {format: 'json'} do
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resource :authentication , :controller => 'authentication'
      resource :user do
        member do
          get :qr_code
        end
      end
    end
  end



  scope "/(:locale)", :locale => /en|es/ do
    resources :cards
    resources :products do
      member do
        get :like
      end
    end

    match '/auth/:provider/callback' => 'sessions#create', :as => :auth_provider_callback
    match '/auth/failure' => 'sessions#failure'
    match "/sessions/signout" => "sessions#destroy", :as => :signout
  end

  
  match "/:locale" => "home#index" , :constraints => {:locale => /en|es/} , :as => :locale_home
  match '/(:locale)/:slug_id' => 'cards#show', :as => :card_landing,  :constraints => {:locale => /en|es/}
  root :to => "home#index"

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/card.rb
class Card
  include Mongoid::Document
  include Mongoid::Timestamps

  field :url , type: String

  embedded_in :user

  def url

  end


  def qr_code(w = 200,h = 200)
    "http://api.qrserver.com/v1/create-qr-code/?data=#{self.url}&size=#{w}x#{h}"
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate_user , :except => [:show, :edit]

  def new
  end

  def show
    @user = User.find_by_slug(params[:slug_id])
    @user.update_stats if request.format == :qrcode
    @title = @user.name + " @"
    respond_to_mobile :show
  end

  def create
    @url = BITLY_CLIENT.shorten("https://www.facebook.com/profile.php?id" + current_user.uid)
    redirect_to @url.url
  end

  def edit
    @user = current_user || User.find_by_slug(params[:id])
    @title = @user.name + " @"
    respond_to_mobile :edit
  end


  def update
    if current_user.update_attributes(params[:user])
      flash[:notice] = "Saved"
    else
      flash[:notice] = "Oooops!"
    end
    redirect_to :back
  end
  
  private
  
  def respond_to_mobile(content)
    respond_to do |format|
      format.mobile {render content}
    end
  end


end

app/helpers/cards_helper.rb
module CardsHelper

  # Show Helpers

  def link_to_add_facebook_friend(user)
     link_to t('cards.helpers.link_to_add_facebook_friend'),
     "http://www.facebook.com/dialog/friends/?id=#{user.facebook_info.uid}&app_id=#{Settings.omniauth.facebook.app_id}&redirect_uri=#{request.url}"
  end

  def link_to_twitter_follow(user)
    link_to t('cards.helpers.link_to_twitter_follow')+ user.twitter_info.user_name, "https://twitter.com/intent/user?screen_name=#{user.twitter_info.user_name}", class: "twitter-follow-button" , target:'_new'
  end

  def link_to_linkedin(user)
    link_to(t("cards.helpers.link_to_linkedin"), user.linkedin_info.profile_url , popup: true)
  end

  def link_to_instagram(user)
    link_to t("cards.helpers.link_to_instagram"), "instagram://user?username=#{user.instagram_info.uid}", popup: true
  end
  
  def link_to_github(user)
    link_to t("cards.helpers.link_to_github"), "https://github.com/#{user.github_info.uid}", popup: true
  end

  # Edit HELPERS
  def link_to_qr_code(user, w=200 ,h = 200)
    link_to "Your QRcode", qrcode_url(card_landing_url(user.slug, :format => :qrcode), w, h)
  end
  
  def image_tag_qr_code(user, w=150 ,h = 150)
    image_tag(qrcode_url(card_landing_url(user.slug, :format => :qrcode), w, h))
  end
  
  def bookmark_qr_code(user, w=150 ,h = 150)
    image_tag(qrcode_url("http://friendscan.me", w, h))
  end

  def qrcode_url(url, w, h)
    "http://qurecode.herokuapp.com/api/qrcode.image?size=#{w}&color=244468&background_color=ffffff&second_color=39c&prettify=true&url=#{url}"
  end

  def link_to_tumblr_follow(user)
    link_to "Follow on Tumblr", "http://www.tumblr.com/follow/#{user.tumblr_info.uid}", popup: true
  end


  def link_to_last_fm(user)
    link_to "Last.fm", user.last_fm_info.profile_url , popup: true
  end


  def link_to_foursquare(user)
    link_to "Foursquare", "https://foursquare.com/#{user.foursquare_info.uid}", popup: true
  end


  def link_to_tumblr(user)
    link_to "Tumblr", "http://#{user.tumblr_info.uid}.tumblr.com/", popup: true
  end

  def link_to_flickr(user)
    link_to "Flickr", "http://www.flickr.com/photos/#{user.flickr_info.profile_id}/", popup: true
  end


end

app/views/cards/edit.haml
.top_bar
  =link_to image_tag("fsm_logo_topbar.png"), "/", :"data-ajax" => "false"
#wrap
  .starburst
    = render :partial => 'flash', :locals => {:flash => flash}
    = render :partial => 'topnav', :locals => { :current_page => 'edit' }
    .vcard-container
      .layer
        .card-header
          - if @user.has_social?(:facebook)
            = image_tag("http://graph.facebook.com/#{@user.facebook_info.uid}/picture", :class => "avatar")
          - elsif @user.has_social?(:twitter)
            = image_tag("https://api.twitter.com/1/users/profile_image?screen_name=#{@user.twitter_info.user_name}", :class => "avatar")
          %h1.name= @user.name
          - if !is_mobile_device?
            = link_to t("cards.edit.view_your_qr_code"), "javascript:void(0)", :class => 'qr-code-link'
            = link_to t("cards.edit.bookmark_your_card"), "javascript:void(0)", :class => 'bookmark-link'
        .panel
          .social
            %ul
              %li.qrcode          
                - if is_mobile_device?
                  #center
                    .image
                      = image_tag_qr_code(@user)
                    .copy-odd
                      %p.qr-link-label
                        Links to:
                        = link_to card_landing_url(@user.slug), card_landing_url(@user.slug)
                      = t('cards.edit.scan_legend_1')
                      %b
                        = t('cards.edit.qr_code_legend_1')
                        = @user.name
                      = t('cards.edit.qr_code_legend_2')
                - else
                  #center.bookmark
                    .image= bookmark_qr_code(@user)
                    .copy-odd
                      %p.qr-link-label
                        %span Links to:
                        = link_to "http://friendscan.me" , "http://friendscan.me"
                      = t('cards.edit.scan_legend_1')
                      %b= t('cards.edit.bookmark_legend_1')
                      = t('cards.edit.bookmark_legend_2')
                  #center.your-qr-code
                    .image
                      = image_tag_qr_code(@user)
                    .copy-odd
                      %p.qr-link-label
                        %span Links to:
                        = link_to card_landing_url(@user.slug), card_landing_url(@user.slug)
                      = t('cards.edit.scan_legend_1')
                      %b
                        = t('cards.edit.qr_code_legend_1')
                        = @user.name
                      = t('cards.edit.qr_code_legend_2')
                %br{:style=> "clear:both"}/
                %li.editshow-share
                  = tweet(t('cards.edit.tweet'), edit_card_url(@user.slug))
                  = facebook_post(t("cards.edit.facebook.name"),
                                  t("cards.edit.facebook.caption"),
                                  t("cards.edit.facebook.description"), 
                                  card_landing_url(@user.slug, :format => :qrcode), 
                                  image_url("apple-touch-icon.png"))
                - if signed_in?
                  - if !current_user.has_social?(:facebook)
                    %li.facebook
                      = link_to t('cards.edit.add_facebook_button') , "/auth/facebook", :"data-ajax" => "false"
                  - if !current_user.has_social?(:twitter)  
                    %li.twitter
                      = link_to t('cards.edit.add_twitter_button'), "/auth/twitter", :"data-ajax" => "false"
                  - if !current_user.has_social?(:linkedin)  
                    %li.linkedin
                      = link_to t('cards.edit.add_linkedin_button') , "/auth/linkedin", :"data-ajax" => "false"
                  - if !current_user.has_social?(:instagram)  
                    %li.instagram
                      = link_to t('cards.edit.add_instagram_button') , "/auth/instagram", :"data-ajax" => "false"
                  - if !current_user.has_social?(:github)  
                    %li.github
                      = link_to t('cards.edit.add_github_button') , "/auth/github", :"data-ajax" => "false"
  = render :partial => 'footer'
  = render :partial => 'google_conversions'

app/views/cards/new.haml
%h1 Cards#new
%p Find me in app/views/cards/new.html.haml


= form_for :card, :url => cards_path do |form| 
  = form.submit "friend scan me"

app/views/cards/new.html.haml
%h1 Cards#new
%p Find me in app/views/cards/new.html.haml


= form_for :card, :url => cards_path do |form| 
  = form.submit "friend scan me"

app/views/cards/show.haml
.top_bar
  =link_to image_tag("fsm_logo_topbar.png"), "/", :"data-ajax" => "false"
#wrap
  .starburst
    = render :partial => 'flash', :locals => {:flash => flash}
    = render :partial => 'topnav', :locals => { :current_page => 'show' }
    .vcard-container
      .layer
        .card-header
          - if @user.has_social?(:facebook)
            = image_tag("http://graph.facebook.com/#{@user.facebook_info.uid}/picture", :class => "avatar")
          - elsif @user.has_social?(:twitter)
            = image_tag("https://api.twitter.com/1/users/profile_image?screen_name=#{@user.twitter_info.user_name}", :class => "avatar")

          %h1.name= @user.name
        .panel
          .social
            %ul
              - if @user.has_social?(:facebook)
                %li.facebook.card-button
                  = link_to_add_facebook_friend(@user)
              - if @user.has_social?(:twitter)    
                %li.twitter
                  = link_to_twitter_follow(@user)
              - if @user.has_social?(:linkedin)    
                %li.linkedin
                  = link_to_linkedin(@user)    
              - if @user.has_social?(:instagram)    
                %li.instagram
                  = link_to_instagram(@user)    
              - if @user.has_social?(:github)    
                %li.github
                  = link_to_github(@user)    
              %li.editshow-share
                = tweet(t("cards.show.tweet"), card_landing_url(@user.slug))
                = facebook_post(t("cards.edit.facebook.name"),
                                t("cards.edit.facebook.caption"),
                                t("cards.edit.facebook.description"), 
                                card_landing_url(@user.slug), 
                                image_url("apple-touch-icon.png"))
                = pinit_button(card_landing_url(@user.slug),
                   image_url("apple-touch-icon.png"),
                   t("cards.edit.facebook.description"))
              %li.get-app.card-button
                = link_to t("cards.show.who_is_scanning_you"), "/auth/facebook", :"data-ajax" => "false"
                %br
    .store-container
      %a{:href => "https://itunes.apple.com/app/id564838321?mt=8"}
        %img{:src => "/assets/app-store.svg", :xlink => "show", :width => "135", :height => "40", :type => "image/svg+xml", :pluginspage => "http://www.adobe.com/svg/viewer/install/"}
    %br{:style => "clear:both"}/
    = render :partial => 'footer'

app/views/cards/show.html.haml
.top_bar
  %a{ :href => "/" }friendscan.me
- if current_user
  .top_nav
    = link_to "Edit", "/cards/#{@user.slug}/edit"
    |
    = link_to "Sign Out", signout_path , :method => :delete 
.vcard-container
  .layer
    = image_tag("http://graph.facebook.com/#{@user.facebook_info.uid}/picture", :class => "avatar")
    %h1.name= @user.facebook_info.user_name
    .panel
      .social
        %ul
          %li.facebook.last-left.last-right
            = link_to_add_facebook_friend(@user)
        %br{:style => "clear:both"}/