config/routes.rb
require 'api_constraints'

Friendscan::Application.routes.draw do

  match "/faq" => "home#faq"
  match "/terms" => "home#terms"
  match "/privacy" => "home#privacy"
  namespace :api, defaults: {format: 'json'} do
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resource :authentication , :controller => 'authentication'
      resource :user do
        member do
          get :qr_code
        end
      end
    end
  end



  scope "/(:locale)", :locale => /en|es/ do
    resources :cards
    resources :products do
      member do
        get :like
      end
    end

    match '/auth/:provider/callback' => 'sessions#create', :as => :auth_provider_callback
    match '/auth/failure' => 'sessions#failure'
    match "/sessions/signout" => "sessions#destroy", :as => :signout
  end

  
  match "/:locale" => "home#index" , :constraints => {:locale => /en|es/} , :as => :locale_home
  match '/(:locale)/:slug_id' => 'cards#show', :as => :card_landing,  :constraints => {:locale => /en|es/}
  root :to => "home#index"

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  has_mobile_fu
  helper_method :signed_in?, :current_user 
  before_filter :set_locale
  before_filter :set_og_tags

  private

  def set_og_tags
    @og_description = t('og.description')
    @og_title = t('og.title')
    @og_url =  "http://friendscan.me"
    @og_icon = "http://friendscan.me/assets/facebook-icon.png"
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user
  end

  def authenticate_user
    unless signed_in?
       redirect_to "/", :notice => "Please sign in first!"
    end
  end


  def set_locale
     session[:locale] = params[:locale] if params[:locale].present?
     I18n.locale = session[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { :locale => I18n.locale }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return title for each page
  def title
    base_title = "FriendScan.Me"
    if @title.nil?
      base_title
    else
      "#{@title} #{base_title}"
    end
  end
 

  def tweet(msg, url)
    link_to "Tweet", "https://twitter.com/share", 
      "data-ajax" => "false", class: "twitter-share-button", 
      "data-url" => url, "data-text" => msg,
      "data-count" => "horizontal",  "data-via" => "friendscanme"
  end

  def facebook_post(name, caption, description, url, picture)
    link_to "Post to Facebook", "http://www.facebook.com/dialog/feed?
                                 app_id=#{Settings.omniauth.facebook.app_id}&
                                 picture=#{picture}&
                                 name=#{name}&
                                 caption=#{caption}&
                                 description=#{description}&
                                 redirect_uri=#{url}",
             "data-ajax" => "false", class: 'fb-post-link', target: '_new'
  end


  def image_url(source)
    "http://#{request.host_with_port}#{image_path(source)}"
  end


  def facebook_like(url)
    "<div class=\"fb-like\" 
         data-href=\"#{url}\" 
         data-send=\"true\" 
         data-layout=\"button_count\" 
         data-width=\"200\" 
         data-show-faces=\"false\" 
         data-font=\"tahoma\">
    </div>"
  end  
end

app/views/application/_facebook_js_sdk.haml
#fb-root
:javascript
    window.fbAsyncInit = function() {
      FB.init({
         appId      : '131951090214210', // App ID
         status     : true, // check login status
         cookie     : true, // enable cookies to allow the server to access the session
         xfbml      : true  // parse XFBML
      });
      #{yield :facebook_javascript}
    };             
    (function(d){
       var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
       if (d.getElementById(id)) {return;}
         js = d.createElement('script'); js.id = id; js.async = false;
         js.src = "//connect.facebook.net/en_US/all.js";
         ref.parentNode.insertBefore(js, ref);
    }(document));

app/views/application/_flash.haml
#flash
  - flash.each do |key, value|
    %div{ :title => key.to_s.humanize, :id => "flash_#{key}" }
      = h value
    %br

app/views/application/_flash.html.haml
#flash
  - flash.each do |key, value|
    %div{ :title => key.to_s.humanize, :id => "flash_#{key}" }
      = h value
    %br

app/views/application/_footer.haml
%footer
  .request
    = link_to "Feature Request or Support?", "http://yetimedia.zendesk.com/home", :target => "_blank"
    &nbsp;|&nbsp;
    = link_to "FAQ", "/faq"
    &nbsp;|&nbsp;
    = link_to "Terms of Service", "/terms"
    &nbsp;|&nbsp;
    = link_to "Privacy Policy", "/privacy"
  .hire-copyright
    Hire 
    = link_to (image_tag ("yeti_logo.png"), :id => "footer_img"), "http://yeti-media.com/"
    &copy; Yeti Media #{Time.now.year}

<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script> 
= javascript_include_tag "//assets.pinterest.com/js/pinit.js"
:plain
  <!-- Place this render call where appropriate -->
  <script type="text/javascript">
    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
  </script>
  

app/views/application/_google_conversions.haml
:plain
  <!-- Google Code for sign up Conversion Page -->
  <script type="text/javascript">
  /* <![CDATA[ */
  var google_conversion_id = 1037785400;
  var google_conversion_language = "en";
  var google_conversion_format = "3";
  var google_conversion_color = "ffffff";
  var google_conversion_label = "cuvcCOKWsAIQuLLt7gM";
  var google_conversion_value = 0;
  if (1) {
    google_conversion_value = 1;
  }
  /* ]]> */
  </script>
  <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
  </script>
  <noscript>
  <div style="display:inline;">
  <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1037785400/?value=1&amp;label=cuvcCOKWsAIQuLLt7gM&amp;guid=ON&amp;script=0"/>
  </div>
  </noscript>

app/views/application/_head.haml
%head
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Maven+Pro'
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lobster&subset=latin'
  = stylesheet_link_tag 'application'
  = stylesheet_link_tag 'http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css'
  %link{ :href => "/assets/icn-fsm2.ico", :rel => "icon" }
  %link{ :href =>"/assets/apple-touch-icon.png", :rel => "apple-touch-icon" }
  %link{ :type => "text/plain", :rel => "author", :href => "/humans.txt"}
  
  = render :partial => "javascripts"

  %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0", :name => "viewport" }/
  %meta{:name => "description", :content => t('og.description')}
  %meta{:name => "keywords", :content => "scan me, qr code generator free, qr code, create qr code, qr code business card generator, qr code create, create your own qr code, qr code iphone, qr code business card, qr code applications, free qr code, quick response code, friend scan me, personalized qr code, qr code marketing, qr code creation, qr code generation, qr code android, qr code download, qr code maker, qr code vcard generator"}
  = render partial: 'og_tags'
  %title #{title}
  

app/views/application/_head.html.haml
%head
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Maven+Pro'
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lobster'
  = stylesheet_link_tag 'application'
  %link{ :href => "/assets/icn-fsm.ico", :rel => "icon" }
  %link{ :href =>"/assets/apple-touch-icon.png", :rel => "apple-touch-icon" }
  = render :partial => "javascripts"
  %meta{:name => "apple-mobile-web-app-capable", :content => "yes" }/
  %meta{:content => "width=device-width; initial-scale=1.0, maximum-scale=1.0", :name => "viewport" }/
  %title #{title}

app/views/application/_javascripts.haml
= javascript_include_tag 'application'
%script{ :type => "text/javascript", :src => "//code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js" }

= yield :javascripts

:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26259181-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/application/_javascripts.html.haml
= javascript_include_tag 'application'

app/views/application/_og_tags.haml
%meta{:content => "friendscan.me", :property => "og:site_name"}/
%meta{:content => "131951090214210", :property => "fb:app_id"}/
%meta{:content => "company", :property => "og:type"}/

%meta{:content => @og_description , :property => "og:description"}/
%meta{:content => @og_title, :property => "og:title"}/
%meta{:content => @og_icon, :property => "og:image"}/
%meta{:content => @og_url, :property => "og:url"}/

app/views/application/_topnav.haml
.top_nav
  .w100      
    = select_tag :locale, options_for_select(['en', 'es'] , params[:locale]), :"data-native-menu" => "false"
  - if current_user
    %p.user_name
      = t('home.welcome')
      = current_user.name
    %p.user_name
      - if current_page == "home"
        = t('nav.home')
      - else
        = link_to t('nav.home'), locale_home_path, :"data-ajax" => "false"
      |
      - if current_page == "edit"
        = t('nav.edit')
      - else
        = link_to t('nav.edit'), edit_card_path(current_user.slug), :"data-ajax" => "false"
      |
      - if current_page == "show"
        = t('nav.show')
      - else
        = link_to t('nav.show'), card_landing_path(current_user.slug), :"data-ajax" => "false"
      |
      = link_to t('nav.products'), products_path, :"data-ajax" => "false"
      |
      = link_to t("nav.sign_out"), signout_path , :method => :delete, :"data-ajax" => "false"
  - else
    - if current_page == "edit"
      = link_to "Login", "/"
    - else