config/routes.rb
require 'api_constraints'

Friendscan::Application.routes.draw do

  match "/faq" => "home#faq"
  match "/terms" => "home#terms"
  match "/privacy" => "home#privacy"
  namespace :api, defaults: {format: 'json'} do
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resource :authentication , :controller => 'authentication'
      resource :user do
        member do
          get :qr_code
        end
      end
    end
  end



  scope "/(:locale)", :locale => /en|es/ do
    resources :cards
    resources :products do
      member do
        get :like
      end
    end

    match '/auth/:provider/callback' => 'sessions#create', :as => :auth_provider_callback
    match '/auth/failure' => 'sessions#failure'
    match "/sessions/signout" => "sessions#destroy", :as => :signout
  end

  
  match "/:locale" => "home#index" , :constraints => {:locale => /en|es/} , :as => :locale_home
  match '/(:locale)/:slug_id' => 'cards#show', :as => :card_landing,  :constraints => {:locale => /en|es/}
  root :to => "home#index"

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  mount_uploader :asset , AssetUploader

  field :name, type: String
  field :description, type: String
  field :url,  type: String
  field :likes, type: Integer, default: 0
  field :visible, type: Boolean , default: true
  slug :name

  belongs_to :user

  validates :name, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user , :except => [:show, :like]

  def index
    @products = @current_user.products.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def show
    @product = Product.find_by_slug(params[:id])
    custom_og_tags
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  def new
    @product = @current_user.products.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
    @product = @current_user.products.find_by_slug(params[:id])
  end

  def create
    @product = @current_user.products.new(params[:product])
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = @current_user.products.find_by_slug(params[:id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = @current_user.products.find_by_slug(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end

  def like 
    @product = Product.find_by_slug(params[:id])
    @product.update_attribute :likes , @product.likes + 1
    render text: ""
  end

  private

  def custom_og_tags
    @og_description = @product.description
    @og_title = @product.name
    @og_url =  product_url(@product)
    @og_icon = @product.asset.icon.url
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.haml
.field
  = f.label :name
  = f.text_field :name
.field
  = f.label :asset
  = f.file_field :asset
  - if f.object.asset.present?
    %br/
    = f.check_box :remove_asset
    = f.label :remove_asset
.field
  = f.label :description
  = f.text_area :description
.field
  = f.label :url, t('products.form.url')
  = f.text_field :url
.field
  = f.check_box :visible
  = f.label :visible , "Visible?"

app/views/products/edit.haml
.top_bar
  =link_to image_tag("fsm_logo_topbar.png"), "/", :"data-ajax" => "false"
#wrap
  .starburst
    = render :partial => 'flash', :locals => {:flash => flash}
    = render :partial => 'topnav', :locals => { :current_page => 'show' }
    .vcard-container
      .layer
        %h1 
          Edit
          = @product.name
          Product
        %h1 QR Code
          = qrcode_url(product_url(@product), 200, 200)
        %br/
        %h1 New Product
        = form_for @product, html: {'data-ajax' => 'false' } do |f|
          = render partial: 'form', locals: {f: f}
          = f.submit "Save", 'data-ajax' => 'false'

app/views/products/index.haml
.top_bar
  =link_to image_tag("fsm_logo_topbar.png"), "/", :"data-ajax" => "false"
#wrap
  .starburst
    = render :partial => 'flash', :locals => {:flash => flash}
    = render :partial => 'topnav', :locals => { :current_page => 'show' }
    .vcard-container
      .layer
        %h1
          Products
          = link_to "New", new_product_path
        %ul
          - @products.each do |product|
            %li
              = link_to(product.name, product)
              |
              Likes:
              = product.likes
              |
              = link_to("Edit", edit_product_path(product))

app/views/products/new.haml
.top_bar
  =link_to image_tag("fsm_logo_topbar.png"), "/", :"data-ajax" => "false"
#wrap
  .starburst
    = render :partial => 'flash', :locals => {:flash => flash}
    = render :partial => 'topnav', :locals => { :current_page => 'show' }
    .vcard-container
      .layer
        %h1 New Product
        = form_for @product, html: {'data-ajax' => 'false' } do |f|
          = render partial: 'form', locals: {f: f}
          = f.submit "Save", 'data-ajax' => 'false'

app/views/products/show.haml
.top_bar
  =link_to image_tag("fsm_logo_topbar.png"), "/", :"data-ajax" => "false"
#wrap
  .starburst
    = render :partial => 'flash', :locals => {:flash => flash}
    = render :partial => 'topnav', :locals => { :current_page => 'show' }
    .vcard-container
      .layer
        %h1= @product.name
        = image_tag @product.asset.url
        = raw facebook_like(product_url(@product))
        = tweet("I like \"#{@product.name}\" on FriendScanMe ", product_url(@product))
        %p= link_to "Product URL", @product.url
    %br{:style => "clear:both"}/
    = render :partial => 'footer'

= content_for :facebook_javascript do
  :plain
    FB.Event.subscribe('edge.create',function(response) {
      $.get("/products/#{@product.slug}/like");
    });


= content_for :javascripts do
  = render :partial => "facebook_js_sdk"